// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTV_LBQCrziWtrqX3AFG_KpTg7Wubqmk',
    appId: '1:683722130650:web:79c42cbbf54fd28acb51e3',
    messagingSenderId: '683722130650',
    projectId: 'note-app-36f27',
    authDomain: 'note-app-36f27.firebaseapp.com',
    storageBucket: 'note-app-36f27.appspot.com',
    measurementId: 'G-17JGZSW0BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASdZQdx8znFDDRr-w4HIPTqJaLMwSgh2M',
    appId: '1:683722130650:android:b194e4d3f93de239cb51e3',
    messagingSenderId: '683722130650',
    projectId: 'note-app-36f27',
    storageBucket: 'note-app-36f27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFh19NBoaFx_xs0OuZfxS49-YNKl2cN8',
    appId: '1:683722130650:ios:7d6e017bf5b4f4d2cb51e3',
    messagingSenderId: '683722130650',
    projectId: 'note-app-36f27',
    storageBucket: 'note-app-36f27.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUFh19NBoaFx_xs0OuZfxS49-YNKl2cN8',
    appId: '1:683722130650:ios:7d6e017bf5b4f4d2cb51e3',
    messagingSenderId: '683722130650',
    projectId: 'note-app-36f27',
    storageBucket: 'note-app-36f27.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKTV_LBQCrziWtrqX3AFG_KpTg7Wubqmk',
    appId: '1:683722130650:web:aa39af4768a80e63cb51e3',
    messagingSenderId: '683722130650',
    projectId: 'note-app-36f27',
    authDomain: 'note-app-36f27.firebaseapp.com',
    storageBucket: 'note-app-36f27.appspot.com',
    measurementId: 'G-NYM2DN3R8D',
  );
}
